/// Flutter icons Costomicon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Costomicon
///      fonts:
///       - asset: fonts/Costomicon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Costomicon {
  Costomicon._();

  static const _kFontFam = 'Costomicon';
  static const _kFontPkg = null;

  static const IconData pulse_oximeter =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blood_pressure_control_tool =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
